version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - '8087:8087'
    volumes:
      - .:/app
    environment:
      PORT: 7855
      MONGO_USERNAME: admin
      MONGO_PASSWORD: super_long_password
      MONGO_HOST: mongodb
      MONGO_PORT: 27017
      MONGO_DB: db

      REDIS_ADDR: redis:6379
      REDIS_PASSWORD: long_password

  interface:
    build:
      context: .
      dockerfile: Dockerfile.interface
    ports:
      - '8086:80'

  mongodb:
    image: mongo
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: super_long_password
    volumes:
      - data_mongo:/data/db

  redis:
    image: redis:latest
    environment:
      - REDIS_PASSWORD=long_password
    command: redis-server --requirepass long_password --databases 16
    ports:
      - '6379:6379'
    volumes:
      - data_redis:/data

volumes:
  data_mongo:
    driver: local
  data_redis:
    driver: local
