version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - '8087:8087'
    volumes:
      - .:/app
    environment:
      PORT: 7855
      MONGO_USERNAME: admin
      MONGO_PASSWORD: super_long_password
      MONGO_HOST: mongodb
      MONGO_PORT: 27017
      MONGO_DB: db

  interface:
    build:
      context: .
      dockerfile: Dockerfile.interface
    ports:
      - '8086:80'

  influxdb:
    image: influxdb:2.0.7
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: admin
      DOCKER_INFLUXDB_INIT_PASSWORD: super_long_password
      DOCKER_INFLUXDB_INIT_ORG: iot
      DOCKER_INFLUXDB_INIT_BUCKET: forlorn
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: super_duper_token
    ports:
      - '8056:8086'
    volumes:
      - data_influx:/var/lib/influxdb2

  mongodb:
    image: mongo
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: super_long_password
    volumes:
      - data_mongo:/data/db

volumes:
  data_influx:
    driver: local
  data_mongo:
    driver: local