services:
  rank-server:
    build:
      context: server
      dockerfile: Dockerfile
      network: host
      args:
        - API_URL=jdis-ia.dinf.usherbrooke.ca:8087
        - TYPE=rank
    ports:
      - '8087:8087'
    environment:
      PORT: 7855
      MONGO_USERNAME: admin
      MONGO_PASSWORD: super_long_password
      MONGO_HOST: localhost
      MONGO_PORT: 27017
      MONGO_DB: db
      DOMAIN: jdis-ia.dinf.usherbrooke.ca
      RANK: RANKED

      REDIS_ADDR: localhost:6379
      REDIS_PASSWORD: long_password
    env_file:
      - .env
    volumes:
      - ssl-certs:/app/certs
    network_mode: 'host'

  unrank-server:
    build:
      context: server
      dockerfile: Dockerfile
      network: host
      args:
        - API_URL=jdis-ia.dinf.usherbrooke.ca:8088
        - TYPE=unrank
    ports:
      - '8088:8087'
    environment:
      PORT: 7855
      MONGO_USERNAME: admin
      MONGO_PASSWORD: super_long_password
      MONGO_HOST: localhost
      MONGO_PORT: 27017
      MONGO_DB: db
      DOMAIN: jdis-ia.dinf.usherbrooke.ca

      REDIS_ADDR: localhost:6379
      REDIS_PASSWORD: long_password
    env_file:
      - .env
    volumes:
      - ssl-certs:/app/certs
    network_mode: 'host'

  mongodb:
    image: mongo
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: super_long_password
    volumes:
      - data_mongo:/data/db
    network_mode: 'host'

  redis:
    image: redis:latest
    environment:
      - REDIS_PASSWORD=long_password
    command: redis-server --requirepass long_password --databases 16
    ports:
      - '6379:6379'
    volumes:
      - data_redis:/data
    network_mode: 'host'

  nginx:
    build:
      context: nginx
      dockerfile: Dockerfile
      network: host
      args:
        - DOMAIN=jdis-ia.dinf.usherbrooke.ca
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ssl-certs:/etc/nginx/ssl

volumes:
  data_mongo:
    driver: local
  data_redis:
    driver: local
  ssl-certs:
    driver: local