version: '3.8'

services:
  app:
    build: .
    ports:
      - '7855:7855'
    volumes:
      - .:/app
    environment:
      PORT: 7855

  influxdb:
    image: influxdb:2.0.7
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: admin
      DOCKER_INFLUXDB_INIT_PASSWORD: super_long_password
      DOCKER_INFLUXDB_INIT_ORG: iot
      DOCKER_INFLUXDB_INIT_BUCKET: forlorn
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: super_duper_token
    ports:
      - '8056:8086'
    volumes:
      - data/influx:/var/lib/influxdb2

  mongodb:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - data/mongo:/data/db