const WS_URL = 'ws://localhost:8087/echo';

const MESSAGE_TYPE = {
  0: 'SPAWN',
  1: 'POSITION',
  2: 'REGISTER',
  3: 'FIRE',
  4: 'GAME_START',
  5: 'GAME_END'
};

const SCALE = 30;

const PLAYER_SIZE = 1 * SCALE;
const PLAYER_SPEED = 1.15 * SCALE;

const PROJECTILE_SIZE = 0.35 * SCALE;
const PROJECTILE_SPEED = 1.75 * SCALE;

const COIN_SIZE = 0.5 * SCALE;

const CELL_WIDTH = 10.0 * SCALE;

export { SCALE, PLAYER_SIZE, PLAYER_SPEED, PROJECTILE_SIZE, PROJECTILE_SPEED, COIN_SIZE, CELL_WIDTH };
export { WS_URL, MESSAGE_TYPE };
