const WS_URL = 'ws://localhost:8087/echo';

const MESSAGE_TYPE = {
  1: 'POSITION',
  4: 'GAME_START',
  5: 'GAME_END'
};

const SCALE = 30;

const PLAYER_SIZE = 1 * SCALE;
const PLAYER_SPEED = 1.15 * SCALE;

const PROJECTILE_SIZE = 0.35 * SCALE;
const PROJECTILE_SPEED = 1.75 * SCALE;

const COIN_SIZE = 0.5 * SCALE;
const BIG_COIN_SIZE = 4.0 * SCALE;
const COIN_SIZES = [COIN_SIZE, BIG_COIN_SIZE];

const CELL_WIDTH = 10.0 * SCALE * 2;

const BLADE_ROTATION_SPEED = 230;
const BLADE_DISTANCE = 1.5 * SCALE;
const BLADE_LENGTH = 1.5 * SCALE;

export { SCALE, PLAYER_SIZE, PLAYER_SPEED, PROJECTILE_SIZE, PROJECTILE_SPEED, COIN_SIZE, BIG_COIN_SIZE, COIN_SIZES, CELL_WIDTH, BLADE_ROTATION_SPEED, BLADE_DISTANCE, BLADE_LENGTH };
export { WS_URL, MESSAGE_TYPE };
