name: Golang-server

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-diretory: ./server

    steps:
      # —— Setup Github Actions      —————————————————————————————————————————————
      - uses: actions/checkout@v4

      # —— Setup Golang environment  —————————————————————————————————————————————
      - name: Setup Go 1.21
        uses: actions/setup-go@v5
        with:
          go-version: '1.21.x'

      # —— Build application         —————————————————————————————————————————————
      - name: Build
        run: go build main.go

      # —— Execute tests             —————————————————————————————————————————————
      - name: Run tests
        run: go test -race ./pkg/...
